name: GraalVM Native Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  native-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'dev'
          java-version: '17'
          components: 'native-image'
          native-image-musl: 'false'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: GraalVM Versions
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version

      - name: Microsoft C/C++ Compiler Version
        if: runner.os == 'Windows'
        run: cl.exe

      - name: Build and run App
        run: |
          javac Main.java
          echo 'Building the native image...'
          native-image Main app
          echo 'Building the static image...'
          native-image --static --libc=musl Main app-static
          echo 'Running the native image...'
          ./app

      - name: Upload ${{ matrix.os }} app binary
        uses: actions/upload-artifact@v3
        with:
          name: app-${{ runner.os }}
          path: app
          if-no-files-found: error

      - name: Uploading ${{ matrix.os }} app static binary
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v3
        with:
          name: app-${{ runner.os }}-static.jar
          path: |
            app-static
          if-no-files-found: error
