name: GraalVM Native Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  native-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup GraalVM CE Dev Build
        uses: graalvm/setup-graalvm@v1
        with:
          version: 'dev'
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print GraalVM Versions
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version

      - name: Microsoft C/C++ Compiler Version
        if: runner.os == 'Windows'
        run: cl.exe

      - name: Build and run App
        run: |
          javac Main.java
          native-image Main app
          ./app

      - name: Upload ${{ matrix.os }} app binary
        uses: actions/upload-artifact@v3
        with:
          name: app-${{ runner.os }}
          path: app*
          if-no-files-found: error


  native-build-musl:
    name: native-image-musl on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup GraalVM CE Dev Build
        uses: graalvm/setup-graalvm@v1
        with:
          version: 'dev'
          java-version: '17'
          components: 'native-image'
          native-image-musl: 'true'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build static app image with musl
        run: |
          javac Main.java
          native-image --static --libc=musl Main app-static
          ./app-static

      - name: Uploading ${{ matrix.os }} app static binary
        uses: actions/upload-artifact@v3
        with:
          name: app-static-${{ runner.os }}
          path: |
            app-static*
          if-no-files-found: error