name: Github Action Test

env:
  author: Suresh
  name: Github Action Test
  deployKey: test 

on:
  push:
    branches: 
      - master
      - release/*
  pull_request:
     branches: 
       - master
  schedule:
       - cron: "0 0 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build "${author}" ,
        echo test, and deploy your project.
