name: Github Action Test

env:
  author: Suresh
  name: Github Action Test
  deployKey: test 

on:
  push:
    branches: 
      - main
      - release/*
  pull_request:
     branches: 
       - main
  schedule:
       - cron: "0 0 * * *"

jobs:
  build:
    name: Build job running on ${{ matrix.os }} for JDK ${{ matrix.java }} ${{ matrix.bin-name }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    env:
      jdk-version: ${{ matrix.java }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java: ['11', '16']
        include:
          # includes a new variable of os specific binary name for the matrix leg matching the os and version
          - os: ubuntu-latest
            bin-name: hello-linux
          - os: macos-latest
            bin-name: hello-mac
          - os: windows-latest
            bin-name: hello-win.exe  
        
    steps:
      - name: Checking out the source code
        uses: actions/checkout@v2    
        id: code-checkout
        timeout-minutes: 2
        if: contains(matrix.os, 'latest')
        env:
          name: checkout 
       
      - name: Backing up/Restore the Gradle cache
        uses: actions/cache@v2
        id: gradle-cache
        continue-on-error: true
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-ga-test-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-ga-test-
            
      - name: Backing up/Restore the Gradle wrapper
        uses: actions/cache@v2
        id: gradle-wrapper
        continue-on-error: true
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-ga-test-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-ga-test-
            
      - name: Set up JDK
        id: setup-jdk
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: ${{ matrix.java }}  
        
      - name: Run a one-line script
        run: |
          echo Hello, world!
          java -version
          
      - name: Step failed
        if: failure()
        run: |
          echo This previous step failed "${author}"
          
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
        
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
        
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
        
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
        
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
        
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"     

  container:
      name: OpenJDK docker image
      runs-on: ubuntu-latest

      container:
       image: openjdk:17-jdk-alpine
       
      steps:
        - name: Checkout Repo
          uses: actions/checkout@v2.3.4
          
        - name: Run java app
          run: |
            java --show-version Main.java
            
        
