name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
  
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ windows-latest ]

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Run Commands
      run: |
        echo "TEMP : $TEMP"
        echo "TMP  : $TMP"
        ls -ltrh c:\tmp
        java -Xlog:gc*:c:\tmp\test-gc-%p.log --version
      shell: bash  
