name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    shell: bash

jobs:
  test:
    name: OpenJDK ${{ matrix.java }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        java: [ '20' ]
        os: [ macos-latest, windows-latest, ubuntu-latest ]

    steps:
      - uses: actions/checkout@v3

      - name: Setup OpenJDK EA ${{ matrix.java }} build
        id: setup-java
        uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: ${{ matrix.java }}
          install: true

      - name: Java options check
        run: |
          java --version
          tmpdir=$(dirname $(mktemp -u))
          echo "Temp Dir = ${tmpdir}"

