name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
  
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Check annotations
      run: |
          echo "::set-output name=gh-workflow-name::github-action-test"
          echo "::debug::This is a debug message. Set ACTIONS_STEP_DEBUG secrets to true"
          echo 'JSON_RESPONSE<<EOF' >> $GITHUB_ENV
          curl https://httpbin.org/json >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
          echo "::notice title=Env File::$GITHUB_ENV"
          cat $GITHUB_ENV
          echo "::notice title=Path file::$GITHUB_PATH"
          cat $GITHUB_PATH
      shell: bash  
