name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
  
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ windows-latest ]

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
        
    - name: Run Commands
      run: |
        echo "TEMP : $TEMP"
        echo "TMP  : $TMP"
        ls -ltrh c:/TEMP
        java -XX:+PrintCommandLineFlags -Xlog:gc*:\"c:/TEMP/test-gc1-$$-%t.log\" --version
        java -XX:+PrintCommandLineFlags -Xlog:gc*:c\:/TEMP/test-gc2-%p-%t.log --version
        ls -ltrh c:/TEMP
      shell: bash  
